// Build script: generates config.js from environment variables
// Used by Vercel during deployment — set env vars in Vercel dashboard
const fs = require('fs')

const config = {
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
}

const missing = Object.entries(config)
  .filter(([, v]) => !v)
  .map(([k]) => k)

if (missing.length) {
  console.warn('⚠ Missing environment variables:', missing.join(', '))
  console.warn(
    '  Set them in Vercel Dashboard → Settings → Environment Variables',
  )
}

const content = `// Auto-generated by generate-config.js — DO NOT edit manually
window.B2B_CONFIG = {
  SUPABASE_URL: '${config.SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${config.SUPABASE_ANON_KEY}',
  GEMINI_API_KEY: '${config.GEMINI_API_KEY}',
};
`

fs.writeFileSync('config.js', content)
console.log('✅ config.js generated successfully')
